"""add_comments_to_interviews

Revision ID: 6c88a8b85f32
Revises: 74aa69f40ed0
Create Date: 2026-02-26 21:40:13.003538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c88a8b85f32'
down_revision: Union[str, None] = '74aa69f40ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('comments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'comments')
    # ### end Alembic commands ###
