"""create_resumes

Revision ID: 6fd8702502b8
Revises: c689be4e5054
Create Date: 2026-02-26 19:00:43.715060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd8702502b8'
down_revision: Union[str, None] = 'c689be4e5054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('screening_result', sa.Enum('PENDING', 'PASSED', 'REJECTED', 'WAITLIST', name='screeningresult'), nullable=True),
    sa.Column('ai_review', sa.Text(), nullable=True),
    sa.Column('hr_review', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_SCREENING', 'PENDING_REVIEW', 'PENDING_INTERVIEW', 'COMPLETED', name='resumestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes')
    # ### end Alembic commands ###
