"""add_position_id_to_question_bank

Revision ID: 74aa69f40ed0
Revises: ceae12193d0f
Create Date: 2026-02-26 20:53:30.474767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74aa69f40ed0'
down_revision: Union[str, None] = 'ceae12193d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_banks', sa.Column('position_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'question_banks', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_banks', type_='foreignkey')
    op.drop_column('question_banks', 'position_id')
    # ### end Alembic commands ###
