"""create_interviews

Revision ID: 98f168b6e8c7
Revises: 6fd8702502b8
Create Date: 2026-02-26 19:02:24.017430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f168b6e8c7'
down_revision: Union[str, None] = '6fd8702502b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('interviewer', sa.String(), nullable=True),
    sa.Column('interview_time', sa.DateTime(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('PENDING', 'PASSED', 'REJECTED', 'WAITLIST', name='interviewresult'), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='interviewstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    # ### end Alembic commands ###
