"""create_question_banks

Revision ID: c689be4e5054
Revises: 66b9cc16e168
Create Date: 2026-02-26 18:59:10.611910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c689be4e5054'
down_revision: Union[str, None] = '66b9cc16e168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_banks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('TECHNICAL', 'MANAGEMENT', 'HR', 'OTHER', name='questioncategory'), nullable=True),
    sa.Column('difficulty', sa.Enum('JUNIOR', 'INTERMEDIATE', 'SENIOR', name='questiondifficulty'), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_banks')
    # ### end Alembic commands ###
