"""add_raw_text_and_markdown_to_resume

Revision ID: ceae12193d0f
Revises: 98f168b6e8c7
Create Date: 2026-02-26 20:34:20.086624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceae12193d0f'
down_revision: Union[str, None] = '98f168b6e8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('resume_markdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'resume_markdown')
    op.drop_column('resumes', 'raw_text')
    # ### end Alembic commands ###
